import { BookDetails } from "@/components/BookDetails";
import { myTheme } from "@/themes";
import { ThemeProvider } from "@emotion/react";
import Head from "next/head";

export default function LivroPage({ data }) {
  return (
    <>
      <Head>
        <title>Livro - {data.nome}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={myTheme}>
        <BookDetails data={data} />
      </ThemeProvider>
    </>
  );
}

export async function getStaticPaths() {
  const { livros } = await import("../../../data/data.json");

  const allPaths = livros.map((path) => {
    return {
      params: {
        id: path.nome,
      },
    };
  });
  return {
    paths: allPaths,
    fallback: false,
  };
}

export async function getStaticProps(context) {
  const id = context?.params.id;
  const { livros } = await import("../../../data/data.json");
  const livro = livros.find((livro) => livro.nome === id);
  return {
    props: {
      data: livro,
    },
  };
}
